/*!
 * reveal.js Slide Labels plugin
 *
 * Reads the first h1/h2/h3 inside <aside class="notes"> for each slide
 * and renders it as a visible label bar on the slide tile in overview mode.
 * The label is invisible during normal presentation.
 */
const Plugin = {

	id: 'slide-labels',

	init( reveal ) {

		const style = document.createElement( 'style' );
		style.textContent = `
			.reveal .slide-label {
				display: none;
				position: absolute;
				bottom: 0;
				left: 0;
				right: 0;
				background: rgba(0, 0, 0, 0.72);
				color: #fff;
				font-weight: bold;
				font-size: 1.4em;
				line-height: 1;
				padding: 0.35em 0.6em;
				text-align: center;
				pointer-events: none;
				z-index: 100;
				box-sizing: border-box;
				white-space: nowrap;
				overflow: hidden;
				text-overflow: ellipsis;
			}
			.reveal.overview .slide-label {
				display: block;
			}
		`;
		document.head.appendChild( style );

		// Run after the deck is fully ready so all slides exist in the DOM,
		// including those generated by the markdown plugin.
		reveal.addEventListener( 'ready', () => {
			reveal.getRevealElement()
				.querySelectorAll( '.slides section:not(.stack)' )
				.forEach( slide => {
					const notes = slide.querySelector( 'aside.notes' );
					if ( !notes ) return;

					const heading = notes.querySelector( 'h1, h2, h3' );
					if ( !heading ) return;

					const label = document.createElement( 'div' );
					label.className = 'slide-label';
					label.textContent = heading.textContent.trim();
					slide.appendChild( label );
				} );
		} );

	}

};

export default () => Plugin;
